### ISSUE TITLE
use VSCode 1.2 extension install

### ISSUE THREAD

**Issue by ctaggart** [ctaggart/rusty-vscode#16]
code 1.2 command line support installing extensions, which obsoletes my curl scripts.

**Comment by ctaggart** [comment]
When I run `code --install-extension saviorisdead.RustyCode` in the `docker build`, I am getting this error:

```
Error: watch /home/vscode/.config/Code/User ENOENT
    at exports._errnoException (util.js:890:11)
    at FSWatcher.start (fs.js:1323:19)
    at Object.fs.watch (fs.js:1351:11)
    at new e (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:6:1245)
    at m (/usr/share/code/resources/app/out/vs/code/node/cli.js:4:11378)
    at t._createInstance (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:6:7605)
    at t._createAndCacheServiceInstance (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:6:8580)
    at t._getOrCreateServiceInstance (/usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:6:7766)
    at /usr/share/code/resources/app/out/vs/code/node/cliProcessMain.js:6:7122
    at Array.map (native)
```

How do I debug “Error: spawn ENOENT” on node.js?
http://stackoverflow.com/a/35677181/23059

**Comment by ctaggart** [comment]
It looks to be an initialization issue of some sort. I can reproduce the error if I haven't launch the code gui and I try to install any extension, such as:

```
code --install-extension Ionide.Ionide-fsharp
code --install-extension ms-vscode.csharp
```

**Comment by ctaggart** [comment]
I just need to create that directory. You can't install an extension is `~/.config/Code/User/` does not exist. I'm able to reproduce the error by removing that directory. I'm able to avoid it by create it.
